// util/PromptCategories.js

export const PROMPT_CATEGORIES = [
    "Men's Portraits",
    "Women's Portraits",
    "Professional Headshots",
    "Product Design",
    "Marketing/Advertising",
    "Poster Design",
    "Logo/Iconography",
    "Interior Design",
    "T-Shirt Graphics",
    "Video Game Assets",
    "Album/Book Cover",
    "Food & Beverage",
    "Pets & Animals",
    "Landscape/Scenery",
    "Cityscapes/Urban",
    "Technical Illustration",
    "Infographics/Data Viz",
    "Children's Education",
    "Fashion (Editorial)",
    "Mascot Design",
    "Mood Boards/Aesthetics",
    "Still Life",
    "Historical Recreations",
    "Sports & Action",
    "Vehicle Art (Cars/Planes)",
    "Dungeons & Dragons (D&D)",
    "Web/UI Backgrounds",
    "Greeting Card Art",
    "Medical/Scientific",
    "Religious/Spiritual",
];